[package]
name = "s2-sys"
version = "0.1.0"
license = "MIT"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "~0.2"
link-cplusplus = { version = "1.0", optional = true }

[build-dependencies]
cmake = "0.1"
pkg-config = "0.3.30"

[lib]
name = "s2_sys"
